[package]
name = "tcx"
version = "0.1.0"
authors = ["Vitaly Merenkov <vmrnkv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.20"
chrono = "0.4.19"